# Generated by Django 5.2.4 on 2025-07-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
