# Generated by Django 5.2.4 on 2025-07-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='custom_fields',
        ),
    ]
